// Popular trips shown with a full day-by-day itinerary.
// Copy and photos come from the GO Tours WeTravel trip pages (prices and dates intentionally left off).
// Each trip builds to <slug>.html and appears on the homepage. Images live in images/<dir>/.
module.exports = [
  {
    slug: 'national-heritage-tour',
    dir: 'heritage',
    name: '8-Day National Heritage Tour',
    short: 'National Heritage Tour',
    hero: 'g12.jpg',
    days: '8 days',
    route: 'Williamsburg · Yorktown · Washington, DC · Gettysburg',
    group: 'Groups of 20 to 54',
    audience: 'Built for homeschool students',
    tagline: 'An unforgettable journey through American history, from Jamestown to Gettysburg.',
    source: 'https://gotours.wetravel.com/trips/go-tours-8-day-fall-homeschool-national-heritage-tour-go-tours-3379177301',
    about: [
      'Join GO Tours for an inspiring 8-day adventure designed especially for homeschool students! This thoughtfully planned tour combines the rich heritage of our nation’s founding with Christian values and educational enrichment. Together, we’ll explore the heart of early American history, walking where patriots once stood and gaining a deeper appreciation for the freedoms we enjoy today.',
      'Our journey begins in the historic towns of Williamsburg and Yorktown, where students will step back in time to the 18th century. Through immersive experiences, costumed interpreters, and hands-on exhibits, they’ll discover the birth of democracy and the faith that guided many of our Founding Fathers. Next, we travel to Washington, D.C., where students will experience the awe of our nation’s capital — visiting iconic monuments, world-renowned museums, and powerful landmarks like the Lincoln Memorial and the U.S. Capitol.',
      'We’ll pause to honor the brave at Arlington National Cemetery, reflect at Mount Vernon, the home of George Washington, and stand in reverence at Fort McHenry, where the Star-Spangled Banner was born. The tour concludes with a powerful visit to Gettysburg, the site of the turning point in the Civil War, where students will learn about sacrifice, leadership, and faith during one of the most critical moments in our history.',
      'This is more than just a field trip — it’s a journey that will build lasting memories, deepen students’ understanding of their Christian heritage in America, and inspire them to be thoughtful, faith-driven citizens.',
    ],
    included: [
      ['user', 'Tour Guide', 'Licensed Christian Tour Guide'],
      ['plane', 'Round Trip Airfare', 'Flight from your airline hub to Washington, DC'],
      ['bus', 'Charter Bus Travel', 'Safe and comfortable coaches'],
      ['ticket', 'Sightseeing Entrances', 'All site admission fees'],
      ['utensils', 'Meals', 'Daily meals upon arrival'],
      ['bed', 'Hotel Accommodations', '3 or 4 star hotels with interior hallways'],
      ['book', 'Tour Books', 'Customized guide and workbook for the trip'],
      ['shirt', 'Group Shirt', 'Shirt designed for your trip'],
      ['heart', 'Tips & Gratuities', 'All tips and gratuities included'],
    ],
    excluded: [['Home Transportation', 'Transportation to and from your home airport'], ['Checked Luggage Fees', 'If applicable'], ['Souvenirs', '']],
    itinerary: [
      { title: 'From Coast to Capital', sub: 'Travel day', img: 'day1.jpg', alt: 'The U.S. Capitol at golden hour',
        stops: ['Flight to Washington, DC', 'First glimpse of the capital', 'Coach to Williamsburg', 'Hotel check-in & dinner'],
        text: [
          'Get ready for takeoff! Today, we’ll meet bright and early at the airport to begin our exciting 8-day journey through American history. As we board our flight to Washington, D.C., we’ll reflect on the incredible adventure ahead—a journey filled with unforgettable sights, hands-on learning, and a deeper understanding of our nation’s Christian roots.',
          'Upon arrival on the East Coast, we’ll begin exploring as time allows. Depending on our arrival time and energy levels, we may catch a few first glimpses of Washington, D.C.—possibly even a quick stop at a monument or memorial. After stretching our legs and taking in the first sights of the capital, we’ll board our comfortable coach bus and head south to the Williamsburg area, where we’ll get settled into our hotel, enjoy dinner, and rest up for a full day of discovery tomorrow!',
        ] },
      { title: 'Foundations of a Nation', sub: 'Jamestown & Yorktown', img: 'day2.jpg', alt: 'Replica ship at Jamestown Settlement',
        stops: ['Jamestown Settlement', 'American Revolution Museum at Yorktown', 'Yorktown Battlefield walking tour', 'Dinner & group reflection'],
        text: [
          'Today we step straight into the pages of early American history! After a hearty breakfast, our first stop is the Jamestown Settlement, where the story of America’s first permanent English colony comes to life. Students will explore full-scale replicas of the three ships that brought settlers across the Atlantic, walk through a re-created Powhatan village, and experience what daily life was like in a 1607 colonial fort. Through hands-on exhibits and engaging interpreters, we’ll see how faith, perseverance, and community helped shape this early settlement.',
          'Next, we’ll head to the American Revolution Museum at Yorktown, where powerful exhibits, films, and outdoor living-history areas paint a vivid picture of the struggles and triumphs of the Revolutionary War. From the causes of the conflict to the lives of soldiers and families, students will get a comprehensive look at the birth of American independence. In the afternoon, we’ll take a guided walking tour of the Yorktown Battlefield, the very site where the British surrendered in 1781. As we walk the historic grounds, students will be challenged to think about the courage and conviction it took to fight for freedom—and how God’s providence played a role in our nation’s founding.',
          'We’ll return to our hotel in Williamsburg for dinner and group reflection, discussing how the day’s experiences connect to our faith, our history, and the freedoms we enjoy today.',
        ] },
      { title: 'Colonial Williamsburg & Monuments of Remembrance', sub: 'Colonial Williamsburg', img: 'day3.jpg', alt: 'Horse-drawn carriage on a Colonial Williamsburg street',
        stops: ['Colonial Williamsburg trades', 'Colonial Capitol Building', 'Vietnam Veterans Memorial', 'Lincoln Memorial', 'Korean War Veterans Memorial'],
        text: [
          'We begin the day immersed in the living history of Colonial Williamsburg, the restored 18th-century capital of Virginia. As we stroll along cobblestone streets and interact with costumed interpreters, students will witness colonial life firsthand—visiting blacksmiths, weavers, apothecaries, and other tradespeople from the era. We’ll step into the Colonial Capitol Building, where early leaders debated laws and shaped the foundation of American democracy. It’s an incredible opportunity to see how faith, character, and vision influenced the decisions that helped launch a new nation.',
          'In the afternoon, we’ll board our bus and head north to the nation’s capital—Washington, D.C. Upon arrival, we’ll begin exploring some of the city’s most powerful and moving memorials. At the Vietnam Veterans Memorial, we’ll reflect on the courage and sacrifice of those who served in a difficult time. At the Lincoln Memorial, we’ll honor the legacy of a president who led our nation through division with deep faith and moral clarity. Finally, at the Korean War Veterans Memorial, we’ll remember the bravery and hardship of soldiers who fought for freedom on distant shores.',
          'As evening falls, students will have time to reflect on the day’s powerful experiences, recognizing the cost of liberty and the value of leadership rooted in faith and purpose.',
        ] },
      { title: 'Halls of Power', sub: 'Capitol Hill', img: 'day4.jpg', alt: 'GO Tours students on the steps in front of the U.S. Capitol',
        stops: ['U.S. Capitol guided tour', 'Library of Congress', 'Supreme Court', 'White House photo stop', 'World War II Memorial', 'Washington Monument'],
        text: [
          'Today we’ll explore the heart of American government, where the principles of justice, liberty, and democracy are lived out each day. Our morning begins with a guided tour of the U.S. Capitol Building, where laws are made and history is shaped. Students will stand in the Rotunda, admire stunning artwork and architecture, and learn how faith and conviction have influenced leaders throughout our nation’s past.',
          'Next, we’ll visit the nearby Library of Congress, the largest library in the world. With its breathtaking architecture and rich collection of knowledge, this stop reminds us of the importance of learning, wisdom, and the pursuit of truth. Just across the street is the Supreme Court, the highest court in the land. We’ll learn how the judicial system works and how the Constitution continues to shape our rights and responsibilities as American citizens.',
          'In the afternoon, we’ll stop for a photo opportunity outside the White House, the residence and workplace of every U.S. president since John Adams. Then we’ll take time to reflect at two more iconic landmarks: the World War II Memorial, honoring the greatest generation’s service and sacrifice, and the towering Washington Monument, a tribute to our first president’s leadership and unwavering faith in God’s providence. As the sun sets over the National Mall, students will gain a deeper appreciation for the institutions and individuals that helped shape our country.',
        ] },
      { title: 'Honor and Heritage', sub: 'Service, sacrifice & leadership', img: 'day5.jpg', alt: 'GO Tours group in front of George Washington’s Mount Vernon',
        stops: ['Marine Corps War Memorial (Iwo Jima)', 'Arlington National Cemetery', 'Changing of the Guard', 'Mount Vernon estate'],
        text: [
          'We begin today with a visit to the powerful Iwo Jima Marine Corps Memorial, officially known as the Marine Corps War Memorial. This iconic statue, inspired by the famous photo of Marines raising the American flag on Iwo Jima during World War II, serves as a lasting tribute to the courage and sacrifice of all Marines who have fought for our country. It’s a humbling reminder of the bravery that has defended our freedoms across generations.',
          'Next, we travel to the serene and sacred grounds of Arlington National Cemetery, where more than 400,000 service members, veterans, and their families are laid to rest. We’ll witness the Changing of the Guard at the Tomb of the Unknown Soldier, a deeply moving ceremony that reflects honor, respect, and precision. As we walk among the rows of white headstones, students will be encouraged to reflect on the cost of freedom and the importance of remembering those who gave their lives for it.',
          'In the afternoon, we journey to Mount Vernon, the beloved estate of George Washington, our nation’s first president. Set along the banks of the Potomac River, this beautifully preserved property offers a glimpse into Washington’s life as a leader, farmer, and man of deep personal faith. Students will explore the mansion, gardens, and museum exhibits, gaining a fuller understanding of the values and vision that helped shape the foundation of the United States. It’s a fitting way to end a day centered on honor, leadership, and legacy.',
        ] },
      { title: 'Lessons from the Past', sub: 'National treasures', img: 'day6.jpg', alt: 'Rotunda of the National Archives',
        stops: ['U.S. Holocaust Memorial Museum', 'Smithsonian museums (your choice)', 'National Archives', 'Ford’s Theatre & Petersen House', 'Evening tour: MLK, FDR & Jefferson Memorials'],
        text: [
          'Today is a powerful and meaningful day as we examine moments in history that challenge us to stand for truth, justice, and compassion. We begin at the United States Holocaust Memorial Museum, where students will encounter the heartbreaking stories of victims and survivors of the Holocaust. Through exhibits and personal accounts, we’ll reflect on the dangers of hatred and the importance of standing up for the dignity and value of every human life—lessons that align with our Christian calling to love our neighbors and defend the oppressed.',
          'Next, we’ll explore the vast Smithsonian Museum Complex, where students can choose from a variety of world-class museums—like the National Museum of American History, the National Air and Space Museum, or the Museum of Natural History. Each museum is filled with incredible artifacts, interactive exhibits, and hands-on learning experiences that make history, science, and culture come alive.',
          'In the afternoon, we’ll visit the National Archives, where students will see the original Declaration of Independence, U.S. Constitution, and Bill of Rights—the very documents that enshrine the freedoms we hold dear. From there, we’ll step into the drama of history at Ford’s Theatre and the Petersen House, where President Abraham Lincoln was shot and later died. These locations offer a powerful reflection on leadership, sacrifice, and the fragility of peace.',
          'We’ll finish the day with a special evening tour of three meaningful memorials. At the Martin Luther King, Jr. Memorial, students will be reminded of the power of faith and nonviolence in the pursuit of justice. The Franklin Delano Roosevelt Memorial shows how leadership during hard times can shape a nation, while the Jefferson Memorial honors one of the key architects of American liberty. Each stop challenges us to think about the kind of leaders God calls us to be in our own lives and communities.',
        ] },
      { title: 'Courage in Conflict', sub: 'Fort McHenry & Gettysburg', img: 'day7.jpg', alt: 'Students unfurling a giant American flag at Fort McHenry',
        stops: ['Fort McHenry, Baltimore', 'Gettysburg Civil War Museum', 'Guided Gettysburg Battlefield tour', 'Gettysburg National Cemetery'],
        text: [
          'Today, we journey into two of the most significant chapters in American history—moments when our nation was tested and heroes rose to defend it. We begin with a visit to Fort McHenry in Baltimore, the birthplace of our national anthem. As we stand on the ramparts where American forces withstood a British bombardment in 1814, students will learn how Francis Scott Key was inspired to write The Star-Spangled Banner. The fort is a powerful symbol of resilience and faith in the face of overwhelming odds.',
          'From there, we travel to Gettysburg, Pennsylvania, the site of the bloodiest and most pivotal battle of the Civil War. We’ll start at the Gettysburg Civil War Museum, where students will explore exhibits, artifacts, and interactive displays that bring to life the stories of soldiers, commanders, and civilians caught in the conflict. Then, with a knowledgeable guide, we’ll tour the Gettysburg Battlefield, walking the grounds where Union and Confederate forces clashed in July 1863. Students will hear how strategy, leadership, and incredible sacrifice shaped the outcome of the war—and the nation’s future.',
          'Our final stop of the day is the Gettysburg National Cemetery, where President Abraham Lincoln delivered his famous Gettysburg Address. Standing among the graves of fallen soldiers, we’ll pause for reflection and prayer, remembering those who gave their lives to preserve the union and the principles of liberty and equality. It’s a solemn and meaningful end to a day that calls us to honor the past, understand the cost of freedom, and carry forward a legacy of courage and conviction.',
        ] },
      { title: 'God’s Word & Journey Home', sub: 'Museum of the Bible & farewell', img: 'day8.jpg', alt: 'Historic Bible on display at the Museum of the Bible',
        stops: ['Museum of the Bible', 'Last look at favorite sites (time allowing)', 'Flight home'],
        text: [
          'We close our incredible journey with a visit to one of the most inspiring stops on our tour—the Museum of the Bible in Washington, D.C. This world-class museum offers students a powerful and immersive experience that traces the history, impact, and truth of God’s Word across centuries and cultures. From ancient manuscripts to high-tech exhibits, students will explore how the Bible has shaped world history, influenced American leaders, and continues to guide lives today. It’s the perfect way to reflect on all we’ve seen and learned, grounding our experience in the eternal truth of Scripture.',
          'If time allows, we may visit additional nearby sites or revisit favorite memorials and museums for one last look. Then, we’ll make our way to the airport, hearts full and minds inspired, ready to return home. As we say goodbye to Washington, D.C., and the memories made along the way, students will carry home more than just souvenirs—they’ll return with a deeper appreciation for God’s hand in our nation’s story, a stronger understanding of their role in it, and a renewed commitment to live out their faith with courage and conviction.',
        ] },
    ],
    gallery: [
      ['g01.jpg', 'Students on the National Mall with the White House behind them'], ['g02.jpg', 'The U.S. Capitol framed by spring blossoms'],
      ['g03.jpg', 'The White House'], ['g04.jpg', 'A student reading at a memorial wall'], ['g05.jpg', 'Washington Monument and blossoms'],
      ['g06.jpg', 'Marine Corps War Memorial'], ['g07.jpg', 'Washington Monument across the Mall'], ['g08.jpg', 'Students at a Gettysburg monument'],
      ['g09.jpg', 'Group at the Lincoln Memorial'], ['g10.jpg', 'Arlington National Cemetery'], ['g11.jpg', 'Martin Luther King, Jr. Memorial'],
      ['g12.jpg', 'Sunset over the Washington Monument'], ['g13.jpg', 'Students by the Reflecting Pool'], ['g14.jpg', 'Marine Corps Sunset Parade at the Iwo Jima Memorial'],
      ['g15.jpg', 'Unfurling the flag at Fort McHenry with a park ranger'], ['g16.jpg', 'Students beside a cannon at Gettysburg'], ['g17.jpg', 'Students at the Tidal Basin'],
      ['g18.jpg', 'The Washington Monument reflected at dusk'], ['g19.jpg', 'Students at the MLK Memorial'], ['g20.jpg', 'Group on the Capitol steps'],
      ['g21.jpg', 'The Lincoln Memorial lit at night'], ['g22.jpg', 'Fort McHenry ramparts'], ['g23.jpg', 'Jamestown replica ships'],
      ['g24.jpg', 'Students holding the Star-Spangled Banner replica'], ['g25.jpg', 'World War II Memorial fountains'], ['g26.jpg', 'Arlington in the fall'],
      ['g27.jpg', 'The Jefferson Memorial at sunset'], ['g28.jpg', 'Navy Memorial at night'], ['g29.jpg', 'Tour leaders and students at the Capitol'],
      ['g30.jpg', 'GO Tours group at the Capitol'],
    ],
  },
];
